// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterMusic: typeof import('./src/components/item/FooterMusic.vue')['default']
    IconList: typeof import('./src/components/home/iconList.vue')['default']
    ItemMusicList: typeof import('./src/components/item/itemMusicList.vue')['default']
    ItemMusicTop: typeof import('./src/components/item/itemMusicTop.vue')['default']
    MorePlayList: typeof import('./src/components/home/morePlayList/morePlayList.vue')['default']
    MusicDetail: typeof import('./src/components/item/MusicDetail.vue')['default']
    PerFm: typeof import('./src/components/home/perFm/perFm.vue')['default']
    PersonalList: typeof import('./src/components/home/personalList.vue')['default']
    Playlist: typeof import('./src/components/home/Playlist.vue')['default']
    RecommendedDaily: typeof import('./src/components/home/RecommendedDaily/RecommendedDaily.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwpierTop: typeof import('./src/components/home/SwpierTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
